### ISSUE TITLE
Problem with this extension

### ISSUE THREAD

**Issue by Denisov21** [mseiler025/sync-split-view#1]
Hi,
I can't find this extension in Brackets Registry!

**Comment by mseiler025** [comment]
Hi @Denisov21 

I did not plan to upload this extension to the registry.  You can install it manually by clicking on "Install from URL..." within Brackets Extension Manager and pasting in this link: https://github.com/mseiler025/sync-split-view

more info here - https://github.com/adobe/brackets/wiki/Brackets-Extensions

Let me know if its not working.

**Comment by Denisov21** [comment]
The exstension is working very well!
